### ISSUE TITLE
Javascript API domain 

### ISSUE THREAD

**Issue by marioramalho** [YanchWare/SocialGap#1]
I am creating an application in Cordova and wanted to use linkedin, but when I run my application, it says I need to set my domain javascript API in my Application linkedin. I've tried with the domain "file: ///" but gives the same error. Does anyone have an idea or a solution to this problem?

Best Regards

**Comment by amenuor** [comment]
Hello,
I think you are having issues with registering your app to communicate with Linkedin backend.
Please read this https://developer.linkedin.com/documents/authentication in order to understand how to register correctly an App on Linkedin. Only then you will be able to use their APIs.
